# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cab67f846a08919dcc1e39ea1f7997bd4a92ad55868fc5bab850bceeff6574e5c407ddae1d6357dcbd8845af2f17bf260a8cc00173e9ea0f954e15e82bf1243

test:
  secret_key_base: f3b094c38c9e608a2233dfe7691fbeca7f1f9aac0f7560dd3bf7e3f9cd80d340dee844808a26767cc643b0267819f3fb94ac4f3f5543caa293070c2a52544c75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
